### ISSUE TITLE
Where to obtain and how to use the binary files for javaparser and javamethodextractor

### ISSUE THREAD

**Issue by zhaoyuehrb** [danielzuegner/code-transformer#12]
Dear Authors,

Thank you so much for open source the great work. I am very new to this, may I ask how to get the java-parser-1.0-SNAPSHOT.jar and JavaMethodExtractor-1.0.0-SNAPSHOT.jar? They are listed as required files under CODE_TRANSFORMER_BINARY_PATH, in parallel with semantic. 

The java_to_ast method requires the file. Without it, the notebook interactive_prediction cannot run too.

I tried to download and use https://jar-download.com/artifacts/com.google.code.javaparser/javaparser/1.0.8/source-code but couldn't make it work. I got error of 'no main manifest attribute, in ./javaparser-1.0.8.jar\n'.

Help will be greatly appreciated!

**Comment by tobias-kirschstein** [comment]
Hi Zhao,

thank you for checking out the Code Transformer!

The `JavaParser` can be found in the [/sub_modules/java-parser](https://github.com/danielzuegner/code-transformer/tree/main/sub_modules/java-parser) directory. There, you can also find a prebuilt [
java-parser-1.0-SNAPSHOT.jar](https://github.com/danielzuegner/code-transformer/tree/main/sub_modules/java-parser/target) that should get you going.
For the interactive_prediction notebook you don't need the `JavaMethodExtractor`. But in case you are curious, you can find it in the [/sub_modules/java-method-extractor](https://github.com/danielzuegner/code-transformer/tree/main/sub_modules/java-method-extractor) directory.

We will add this to the documentation, it is not obvious from the README. 
Thanks for pointing it out.

**Comment by zhaoyuehrb** [comment]
Thank you so much! I found the jars and they work fine!
