### ISSUE TITLE
Missing 'Experiment' Class Definition

### ISSUE THREAD

**Issue by zhaoyuehrb** [danielzuegner/code-transformer#13]
Hi Authors,

Thanks for open source the awesome code!

In experiment.py, it tries to "from sacred import Experiment", but I couldn't really find the its definition anywhere, inside or outside 'code_transformer.utils.sacred'. Afterwards the code defines "ex = Experiment(base_dir='../../', interactive=False)", and use 'ex' in quite some places too.

May I enquire if it is something critical, and where to find it?

Thank you so much!

Regards,

**Comment by tobias-kirschstein** [comment]
Hi Yue,

you are right. The `sacred` package was missing in the dependencies.
It is only needed if you want to preprocess your own dataset or train a new model. For playing around with our already trained models you should be good without it.
In any case, I added it to the requirements. Thanks for reporting.
Running `pip install sacred==0.8.1` should fix the problem on your side.

Best, 
Tobias

**Comment by zhaoyuehrb** [comment]
Thank you so much for quick reply! it works now.
I assumed it's some self-written function and didn't even google sacred. My bad. Thanks for your help!
