### ISSUE TITLE
Code embeddings

### ISSUE THREAD

**Issue by emsi** [danielzuegner/code-transformer#21]
First of all thanks for publishing such great work. 

In the example notebook you are showing how to use  "Query Stream Embedding of the masked method name token in the final encoder layer" as "meaningful embedding of the provided AST/Source code pair".  Typically I would use the embedding of [CLS] token. Is the [CLS] token added underneath when I use the processing from the notebook or should I add it myself?

**Comment by tobias-kirschstein** [comment]
Hi Mariusz,

thank you for your interest in the Code Transformer.
For an example Python snippet, the encoder uses the following Attention Mask:
![grafik](https://user-images.githubusercontent.com/6200099/161949123-da4601b4-3e4b-4434-9293-1af09771f562.png)
This means that both the `[CLS]` (split into 5 subtokens) and the method name masking token `[CLS_10]` can attend everything except the method name masking token.
All other tokens can neither attend the `[CLS]` nor the method name masking token. 
For the Transformer Decoder, you can allow the other tokens to attend to the `[CLS]` token via the `attend_cls_token` config (which defaults to `False`).

In the notebook, you can obtain the content stream embeddings of the last layer (`-1`) via `encoder_output.all_emb[-1][0]  # [SEQ_LEN, 1, 1024]`.
E.g., `encoder_output.all_emb[-1][0][0]` would be the embedding of the `[CLS]` token.

Hope, this helps.

Best,
Tobias

**Comment by emsi** [comment]
Thank you. Now it makes perfect sense. Also thank you for updating the notebook and specifying the `content_stream_embeddings` and `query_stream_embeddings` locations. 

p.s. I've noticed that there is also `out_emb` in the returned named tuple that can be used even without requesting all embeddings, so one can simply `model.lm_encoder.forward_batch(batch).out_emb` to access query string embeddings.
