### ISSUE TITLE
Data is not available

### ISSUE THREAD

**Issue by czq1999** [danielzuegner/code-transformer#23]
Hi！ There is something wrong with the data.
![image](https://user-images.githubusercontent.com/49108847/177909868-db9a3e3d-7b30-4d66-8a58-9362a044fab7.png)

Internal Server Error.
How can I get the data and checkpoint? Thanks!

**Comment by tobias-kirschstein** [comment]
Hi, thanks for your interest in the Code Transformer. 
Which files did you attempt to download? I tried a few datasets and checkpoints, and the download worked for all.

Best,
Tobias
